### ISSUE TITLE
WCM Branding Colors

### ISSUE THREAD

**Issue by kathoffman** [nt-williams/wcmtheme#1]
Consider making a function which returns the WCM branding colors!!!

**Comment by nt-williams** [comment]
@hoffmakl

Now has function `wcmtheme::wcm_palette(palette_name, n, type)`. 

See `?wcmtheme::wcm_palette()` for further information.

### Examples

``` r
wcmtheme::wcm_palette("primary", 4)
```

![](https://i.imgur.com/9ixwM17.png)

``` r
wcmtheme::wcm_palette("primary", 10, type = "continuous")
```

![](https://i.imgur.com/vmlUDlR.png)

<sup>Created on 2019-09-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
