### ISSUE TITLE
downstream error from rmarkdown package update

### ISSUE THREAD

**Issue by kathoffman** [nt-williams/wcmtheme#8]
[New Rmarkdown package update removed the `smart_extension` function](
https://github.com/rstudio/rmarkdown/issues/1774), resulting in this error when knitting Rmd files with the `wcmtheme`:

```
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'smart_extension' not found
Calls: <Anonymous> ... create_output_format -> do.call -> <Anonymous> -> ::: -> get
Execution halted
```

**Comment by nt-williams** [comment]
Fixed! thanks @hoffmakl 😄
